#!/usr/bin/env python3
"""
    atcpress - Daemon class for atcpress
"""
import sys
from typing import Dict, Any
import configparser
from libby.daemon import LibbyDaemon
from hispec.util.inficon.inficonvgc502 import InficonVGC502


class AtcPress(LibbyDaemon):
    """ Daemon class for atcpress """
    peer_id = "atcpress"
    bind = "tcp://*:5555"
    address_book = {
        #"atcpress": "tcp://192.168.29.:5555",
        "peer-A": "tcp://127.0.0.1:5556"
    }
    dev = None
    host = None
    port = None
    discovery_enabled = True
    discovery_interval_s = 2.0

    def _must(self, name:str):
        """ checks if the given name exists """
        if "bind" in name:
            return self.bind
        if "address_book" in name:
            return self.address_book
        if "peer_id" in name:
            return self.peer_id
        return None

    def on_start(self, libby):
        """on start set up the daemon from config and initialize device"""
        cfg = configparser.ConfigParser()
        cfg.read("hsfei.config")
        self.host = cfg.get("Device Control", "atcpress_host")
        self.port = int(cfg.get("Device Control", "atcpress_port"))
        self.dev = InficonVGC502()
        self.add_services({
            "connect":      lambda p: self.connect(),
            "disconnect":   lambda p: self.disconnect(),
            "get.data":     lambda p: self.get_data(p.get("item")),
            "set.units":    lambda p: self.set_pressure_unit(p.get("unit_code"))
        })

        self.dev.connect(self.host, self.port)
        if self.dev.is_connected():
            #publish to libby
            libby.publish("atcpress", {"Daemon Startup": "Success"})
        else:
            libby.publish("atcpress", {"Daemon Startup": "Failed"})

    def on_stop(self, libby):
        """Disconnect and let user know"""
        self.dev.disconnect()
        if self.dev.is_connected():
            libby.publish("atcpress", {"Daemon Shutdown": "Failed"})
        else:
            libby.publish("atcpress", {"Daemon Shutdown": "Success"})

    def connect(self) -> Dict[str, Any]:
        """handles connection"""
        self.dev.connect(self.host, self.port)
        if self.dev.is_connected():
            return {"Connect": "Success"}
        return {"error": "Connect Failed"}

    def disconnect(self) -> Dict[str, Any]:
        """handles disconnection"""
        self.dev.disconnect()
        if self.dev.is_connected():
            return {"error": "Disconnect failed"}
        return {"Disconnect": "Success"}

    def get_data(self, item: str) -> Dict[str, Any]:
        """handles getting data"""

        controller_data = self.dev.get_atomic_value(item)
        if controller_data == sys.float_info.max:
            return {"error": "Data not acquired"}
        return {item: controller_data}

    def set_pressure_unit(self, unit_code: int = 1) -> Dict[str, Any]:
        """handles setting pressure unit

        :param unit_code: 0 - mbar, 1 - Torr, 2 - Pascal, 3 - Micron, 4 - hPascal, 5 - Volt
        """
        if self.dev.set_pressure_unit(unit_code):
            return {"Punit": self.dev.get_pressure_unit()}
        return {"error": "Pressure unit not set"}


if __name__ == "__main__":
    atcpress = AtcPress()
    atcpress.serve()
