#!/usr/bin/env python
"""
Simple script for stage control during FEI alignment.
Stage: Gimbal Mount (PGM1SE_M/PPC102)
06/06/2025 - Elijah.AB
"""

import sys
from hispec.util.thorlabs.ppc102 import Ppc102Controller #pylint: disable= E0401,E0611

HOST = '192.168.29.100'

def point_gimbal(x: int, y: int):
    """Point the gimbal to the specified x and y positions."""
    dev = Ppc102Controller(log = False)
    dev.connect(host=HOST, port = PORT)
    try:
        ret = dev.get_enable(channel = 0)
        if ret[0] == 2 or ret[1] == 2:
            print("Enabling Stage")
            dev.set_enable(channel = 0, enable = 1)
        if not dev.is_loop_closed(channel = 0):
            print("Closing Loops")
            dev.set_loop(channel = 0, loop = 2)
        dev.set_pos(channel = 1, pos = x)
        dev.set_pos(channel = 2, pos = y)
        x_cur = dev.get_pos(channel = 1)
        y_cur = dev.get_pos(channel = 2)
        print(f"Curent position: x: {x_cur} , y: {y_cur} ")
    finally:
        dev.disconnect()

def status():
    """Get the current status of the gimbal."""
    dev = Ppc102Controller(log = False)
    dev.connect(host=HOST, port = PORT)
    try:
        ret = dev.get_enable(channel = 0)
        if ret[0] == 2 or ret[1] == 2:
            print("Enabling Stage")
            dev.set_enable(channel = 0, enable = 1)
        if not dev.is_loop_closed(channel = 0):
            print("Closing Loops")
            dev.set_loop(channel = 0, loop = 2)
        x_cur = dev.get_pos(channel = 1)
        y_cur = dev.get_pos(channel = 2)
        print(f"Curent position: x: {x_cur} , y: {y_cur} ")
    finally:
        dev.disconnect()

def cleanup_gimbal():
    """Cleanup the gimbal by opening loops and setting voltages to 0."""
    dev = Ppc102Controller(log = False)
    dev.connect(host=HOST, port = PORT)
    try:
        dev.set_enable(channel = 0, enable = 1)
        print("Loops Open")
        dev.set_loop(channel = 0, loop = 1)
        print("Voltages to 0")
        dev.set_output_volts(channel = 1, volts = 0)
        dev.set_output_volts(channel = 2, volts = 0)
    finally:
        dev.disconnect()

def loop_state(state):
    """Set the loop state of the gimbal."""
    dev = Ppc102Controller(log = False)
    dev.connect(host=HOST, port = PORT)
    try:
        if state not in [0, 1]:
            print("Loop state must be 0 (open) or 1 (closed)")
            dev.disconnect()
            return
        if state == 1:
            print("Setting loop state to 'closed'")
            dev.set_loop(channel=0,loop=2)
        else:
            print("Setting loop state to 'open'")
            dev.set_loop(channel=0,loop=1)

        if dev.is_loop_closed(channel = 0):
            print("Loops Closed")
        else:
            print("Loops Open")
    finally:
        dev.disconnect()

if len(sys.argv) < 3:
    print("Format for this Script is: 'gimbal {red/blue} {cleanup/goto} {x} {y}'")
    sys.exit(0)

if sys.argv[1].lower() == "red":
    PORT = 10012
elif sys.argv[1].lower() == "blue":
    PORT = 10013
else:
    print("Format for this Script is: 'gimbal {red/blue} {cleanup/goto} {x} {y}'")
    sys.exit(0)

if sys.argv[2].lower() == "cleanup":
    cleanup_gimbal()
elif sys.argv[2].lower() in "loops":
    loop_state(int(sys.argv[3]))
elif sys.argv[2].lower() == "goto":
    if len(sys.argv) < 5:
        print("Format for this Script is: 'gimbal {red/blue} {cleanup/goto} {x} {y}'")
        sys.exit(0)
    try:
        xpos = float(sys.argv[3])
        ypos = float(sys.argv[4])
        point_gimbal( xpos, ypos)
        # Use num1 and num2 as integers
    except ValueError:
        print("Error: Invalid integer argument.")
    except IndexError:
        print("Error: Not enough arguments provided.")
elif sys.argv[2].lower() == "status":
    status()

else:
    print("Format for this Script is: 'gimbal {red/blue} {cleanup/goto/status} {x} {y}'")
    sys.exit(0)
