#!/usr/bin/python3
"""
    calyjrack.py - Daemon class for calyjrack
"""
from typing import Dict, Any
import configparser
from libby.daemon import LibbyDaemon
from hispec.util.onewire.onewire import ONEWIRE

def connect(controller: ONEWIRE, host:str, port:int):
    """handles connection"""
    try:
        controller.connect(host, port)
    except Exception as e:
        return {"Connect": f"Failed: {e}"}
    return {"Connect": "Success"}

def disconnect(controller: ONEWIRE):
    """handles disconnection"""
    try:
        controller.disconnect()
    except Exception as e:
        return {"Disconnect": f"Failed: {e}"}
    return {"Disconnect": "Success"}

def get_data(controller: ONEWIRE, host:str, port:int):
    """handles getting data"""
    controller.connect(host, port)
    return {"sensor_data": controller.get_data()}

class CalYJRack(LibbyDaemon):
    """ Daemon class for yjcalrack """
    peer_id = "calyjrack"
    bind = "tcp://*:5555"
    address_book = {
        #"calyjrack": "tcp://192.168.29.:5555",
        "pi_1_daemon": "tcp://131.215.200.218:5560"
    }
    dev = None
    host = None
    port = None
    discovery_enabled = True
    discovery_interval_s = 2.0

    services = {
        "connect":      connect,
        "disconnect":   disconnect,
        "get_data": get_data
    }

    def on_start(self, libby):
        """on start set up the daemon from config and initialize device"""
        cfg = configparser.ConfigParser()
        cfg.read("hsmet.conf")
        self.host = cfg.get("Device Control", "calyjrack_host")
        self.port = int(cfg.get("Device Control", "calyjrack_port"))
        self.dev = ONEWIRE()
        try:
            self.dev.connect(self.host, self.port)
            #publish to libby
            libby.publish("calyjrack", {"Daemon Startup": "Success"})
        except Exception as e:
            #publish failure
            libby.publish("calyjrack", {"Daemon Startup": "Failed", "Connection Error": f"{e}"})

    def on_stop(self, libby):
        """Disconnect and let user know"""
        try:
            self.dev.disconnect()
            libby.publish("calyjrack", {"Daemon Shutdown": "Success"})
        except Exception as e:
            libby.publish("calyjrack", {"Daemon Shutdown": "Failed", "Error":f"{e}"})

    def on_req(self, key: str, payload: Dict[str, Any], ctx: Dict[str, Any]) -> Dict[str, Any]:
        """ set up pipe to functions that execute controls """

        try:
            match key:
                case "connect":
                    return {"connect":connect(self.dev, self.host, self.port)}
                case "disconnect":
                    return {"disconnect":disconnect(self.dev)}
                case "initialize":
                    return {"initialize":get_data(self.dev)}
                case _:
                    return {"ok": False, "error": f"unknown key {key}"}
        except Exception as e:
            return {"ok": False,
                    "error": f"Exception {e} during handling of key {key}"}


if __name__ == "__main__":
    calyjrack = CalYJRack()
    calyjrack.serve()
